<?php
declare(strict_types=1);
require_once __DIR__ . '/lib.php';
if (!is_logged_in()) { http_response_code(403); exit; }
$today = stats_today(); $tz = new DateTimeZone(STATS_TIMEZONE);
$from = DateTimeImmutable::createFromFormat('!Y-m-d', (string)($_GET['from'] ?? $today->format('Y-m-d')), $tz);
$to = DateTimeImmutable::createFromFormat('!Y-m-d', (string)($_GET['to'] ?? $today->format('Y-m-d')), $tz);
if (!$from || !$to || $from > $to || $from < $today->modify('-29 days') || $to > $today) { http_response_code(400); exit; }
$filters=['type'=>stats_event_filter((string)($_GET['type']??''),['','page_view','product_view','other']),'country'=>substr(trim((string)($_GET['country']??'')),0,80),'city'=>substr(trim((string)($_GET['city']??'')),0,80),'client'=>stats_event_filter((string)($_GET['client']??''),['','browser','known_bot','suspected_automation','unknown']),'device'=>stats_event_filter((string)($_GET['device']??''),['','mobile','desktop','tablet','bot','unknown'])];
$rows=[]; for($day=$from;$day<=$to;$day=$day->modify('+1 day')) { $file=STATS_EVENT_DIR.'/'.$day->format('Y-m-d').'.jsonl'; if(!is_file($file)) continue; foreach(file($file, FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[] as $line){$r=json_decode($line,true); if(!is_array($r))continue;$type=(string)($r['event_type']??'');if(($filters['type']==='other'&&in_array($type,['page_view','product_view'],true))||($filters['type']!==''&&$filters['type']!=='other'&&$type!==$filters['type'])||($filters['country']!==''&&($r['country']??'')!==$filters['country'])||($filters['city']!==''&&($r['city']??'')!==$filters['city'])||($filters['client']!==''&&($r['client_class']??'')!==$filters['client'])||($filters['device']!==''&&($r['device_class']??'')!==$filters['device']))continue;$rows[]=$r;}}
usort($rows,static fn($a,$b)=>strcmp((string)($a['timestamp']??''),(string)($b['timestamp']??'')));
$filename='mgoutlet-events-'.$from->format('Y-m-d').($from==$to?'':'-do-'.$to->format('Y-m-d')).'.csv'; header('Content-Type: text/csv; charset=UTF-8'); header('Content-Disposition: attachment; filename="'.$filename.'"'); header('Cache-Control: no-store'); echo "\xEF\xBB\xBF"; $out=fopen('php://output','w'); fputcsv($out,['timestamp','date','time','event_type','path','country','region','city','device_class','client_class'],';'); foreach($rows as $r){$dt=new DateTimeImmutable((string)($r['timestamp']??'')); fputcsv($out,[$dt->format('Y-m-d H:i:s'),$dt->format('Y-m-d'),$dt->format('H:i:s'),$r['event_type']??'',$r['path']??'',$r['country']??'',$r['region']??'',$r['city']??'',$r['device_class']??'',$r['client_class']??''],';');}
